---
title: "Clasificador de Imágenes del Cielo"
author: Ana Blasco, Irene Barba, Lucía Benages, Xueyao An, Roberto Arevalillo, Adriana
  Marí
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: '3'
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción al Problema


## Objetivo del Proyecto

El presente trabajo se enmarca dentro del ámbito del ánalisis digital de señales, aplicando técnicas de procesamiento de imágenes para la resolución de un problema de clasificación automática. El objetivo principal del proyecto es desarrollar un sistema capaz de etiquetar imágenes basándose exclusivamente en la información visual del cielo.

Distinguimos dos problemas de clasificación distintos: 

1. Clasificación Temporal: se pretende determinar el momento del día en el que fue tomada la imagen, distinguiendo entre 3 clases: Día, Noche y Crepúsculo.

2. Clasificación Meteorológica: esta tarea se centra en evaluar las condiciones atmosféricas, buscando diferenciar patrones asociados a cielos despejados frente a cielos cubiertos (nublados).

A diferencia de los enfoques modernos basados en aprendizaje profundo (*Deep Learning*), este proyecto se centra en la extracción de características manual, tratando de identificar, extraer y analizar variables específicas de la señal de imagen — como componentes de color, brillo o texturas — que permitan discriminar las clases de forma lógica e interpretable.

Para la etapa de clasificación, se emplearán técnicas de Aprendizaje Automático (*Machine Learning*), utilizando concretamente el algoritmo Random Forest. Este modelo se basa en el ensamblaje de múltiples árboles de decisión que operan en conjunto, agregando sus predicciones individuales para obtener un resultado más robusto y menos propenso al sobreajuste que un único árbol.

## Origen de los Datos, Distribución y Balance de Clases

Las imágenes utilizadas en este proyecto se han recopilado a partir de diversas fuentes, con el objetivo de construir un dataset representativo y equilibrado para ambos problemas de clasificación. En primer lugar, se recopiló un conjunto masivo de entrenamiento proveniente de fuentes públicas y, en segundo lugar, se generó un conjunto de test independiente compuesto exclusivamente por fotografías propias de los miembros del grupo. 

En lo referente al conjunto de entrenamiento para la clasificación temporal, utilizamos el "Time of Day Dataset" disponible en Kaggle. Este repositorio nos proporcionó un total de 2.661 imágenes, distribuidas en 920 imágenes para la clase de día, 756 para la noche y 985 para el crepúsculo. Esta distribución ofrece una cantidad suficiente y equilibrada de muestras por categoría que permite un entrenamiento adecuado del modelo sin necesidad de aplicar técnicas adicionales de balanceo de clases.

Para la clasificación meteorológica de entrenamiento, fue necesario realizar una fusión de distintas fuentes debido a la escasez de imágenes de cielos despejados en los datasets públicos 
consultados. Partimos del dataset "Clouds Photos" de Kaggle, del cual obtuvimos las 826 imágenes que conforman la clase nublado y apenas 124 imágenes de cielo despejado. Realizamos una búsqueda exhaustiva de otros conjuntos de datos de cielos despejados tanto en Kaggle como en otros repositorios públicos, sin embargo, las imágenes que encontramos no mostraban realmente cielos despejados sino parcialmente nublados, por lo que consideramos que no eran adecuadas para nuestro propósito ya que podían inducir a errores en el entrenamiento del modelo. Tras varios intentos sin éxito, decidimos ampliar la cantidad de imágenes de cielo despejado recurriendo a la plataforma de imágenes de stock libre Unsplash. Mediante una búsqueda manual bajo el término "*clear blue sky*", integramos 583 imágenes adicionales a la clase despejado. De este modo, el conjunto de entrenamiento meteorológico alcanzó un total de 1.533 imágenes, logrando un balance mucho más adecuado con 707 imágenes para la clase despejado y 826 para la clase nublado.

Por otro lado, para la fase de evaluación final (Test), optamos por no reservar un porcentaje de los datasets de entrenamiento, sino generar un conjunto de datos totalmente nuevo a partir de las galerías de fotos de los miembros del grupo. Esta estrategia nos permite comprobar el comportamiento del modelo ante imágenes cotidianas y no vistas previamente, asegurando una evaluación más realista de su capacidad de generalización. Este conjunto de test fue diseñado para estar perfectamente balanceado: para el problema temporal se utilizaron 120 imágenes (40 de día, 40 de noche y 40 de crepúsculo), mientras que para el problema meteorológico se seleccionaron 100 imágenes (50 de despejado y 50 de nublado).

Analizando la distribución global de los datos, observamos que la proporción entre entrenamiento y test ronda el 95% para entrenamiento y un 5% para test en ambos problemas. Mientras que los datos de entrenamiento presentan ligeras variaciones naturales en la cantidad de muestras por clase debido a la disponibilidad de imágenes en las fuentes originales, el conjunto de test manual fue forzado a una equidad exacta (33% por clase en temporal y 50% en meteorológico), lo cual se consideró fundamental para asegurar que las métricas de evaluación final, como la tasa de acierto (*accuracy*), sean fiables y no se vean distorsionadas por el predominio de una clase mayoritaria.

# Preprocesamiento de Imágenes

En esta fase del proyecto, el objetivo principal fue adaptar las imágenes originales para que la extracción de características posterior fuera lo más fiable posible. Dada la naturaleza distinta de los dos problemas a resolver, se optó por aplicar una estrategia de preprocesado diferenciada ya que no todas las imágenes requieren el mismo tratamiento: mientras que en algunos casos el entorno aporta información relevante, en otros puede introducir ruido que confunda al clasificador.

## Preprocesado para Clasificación Temporal 

Para el problema de clasificación temporal, tomamos la decisión de no realizar recortes y trabajar con la imagen completa. Esto se debe a que la distinción entre el día y la noche no reside únicamente en el cielo, sino en el contexto global de la imagen el cual puede aportar información visual relevante que se perdería al aislar la región superior. Por ejemplo, en una imagen de crepúsculo, los tonos anaranjados característicos se concentran casi siempre en la línea del horizonte, por lo que recortar solo la parte superior del cielo, se podría perder esa franja de color quedando un cielo azul genérico que podría confundirse con una imagen diurna. Otro ejemplo ilustra la distinción entre día y noche, donde un cielo oscuro podría ser deberse a una gran tormenta, pero si se observan focos de luz como farolas o ventanas encendidas en la parte inferior de la imagen, se puede llegar a concluir que es de noche. 

No obstante, aunque se preservó la imagen completa, fue necesario asegurar la consistencia de las dimensiones entre los distintos conjuntos de datos. Al analizar el dataset de entrenamiento, observamos que este ya se encontraba preprocesado y estandarizado a una resolución uniforme de 224x224 píxeles. Por el contrario, las imágenes del conjunto de test (provenientes de galerías personales) presentaban resoluciones muy dispares, lo que podría introducir sesgos numéricos en la extracción de características debido a la variabilidad en la cantidad de píxeles y detalles presentes en cada imagen.

Por este motivo, el proceso de normalización de escala se aplicó exclusivamente a las imágenes del conjunto de test, con el objetivo de alinearlas con las dimensiones del entrenamiento. Se fijó el lado mayor de cada imagen a un máximo de 224 píxeles, utilizando un reescalado proporcional. A diferencia de un recorte forzado, esta técnica respeta la relación de aspecto original de la fotografía, ya sea vertical u horizontal, asegurando que ninguna dimensión exceda el límite establecido sin deformar el contenido visual ni alterar las formas de los objetos de la imagen. 

## Preprocesado para Clasificación Meteorológica

Por el contrario, para la clasificación meteorológica, el enfoque fue opuesto. El objetivo es evaluar las condiciones atmosféricas, por lo que cualquier elemento que no pertenezca al cielo como edificios, montañas o vegetación, constituye ruido visual que podría confundir al clasificador, extrayendo características de elementos de la imagen no relevantes. Por ejemplo, una fachada blanca podría confundirse con una nube. Por ello, desarrollamos un algoritmo de segmentación específico para aislar una Región de Interés (ROI) que contuviera exclusivamente información del cielo, descartando el resto de la fotografía.

El algoritmo no se limita a realizar un recorte estático, sino que busca la mejor zona de cielo siguiendo una lógica de cuatro pasos:

  1. Restricción del Espacio de Búsqueda: el algoritmo limita su análisis estrictamente al 40% superior de la imagen, asumiendo que en la imagen, el horizonte y los elementos terrestres suelen ocupar la mitad inferior, mientras que el cielo siempre se ubica en la zona de arriba.

  2. Ventana Deslizante: se emplea una ventana cuadrada cuyo tamaño se ajusta dinámicamente a las dimensiones de cada imagen. Por defecto, la longitud del lado se establece en un tercio del ancho total de la imagen, asegurando una muestra representativa, aunque este tamaño se reduce automáticamente si excede la altura de la zona del cielo (el 40% superior). Una vez definido el tamaño, la ventana escanea 3 posiciones estratégicas a lo largo del eje horizontal: el extremo izquierdo, el centro y el extremo derecho. Esta búsqueda permite encontrar un trozo de cielo libre de obstáculos.

  3. Criterio de Selección: para elegir el recorte óptimo entre los candidatos, se evalúan dos métricas: la homogeneidad (buscando la menor desviación típica, ya que el cielo suele ser más liso que los objetos sólidos) y la luminosidad (descartando zonas con brillo insuficiente para evitar seleccionar siluetas oscuras que no sean cielo). El recorte final se selecciona como aquel que minimiza la desviación típica siempre que su brillo medio supere un umbral predefinido.
  
  4. Normalización Final: el recorte seleccionado se redimensiona a un estándar de 224x224 píxeles. Esto garantiza que todas las muestras de entrada para el clasificador tengan exactamente las mismas dimensiones, independientemente del tamaño original de la imagen. Con ello, se evita que las diferencias de resolución introduzcan sesgos numéricos en el cálculo de las características.
  
El resultado de este proceso es una colección de imágenes que contienen la región de cada imagen con mayor porcentaje de cielo, estandarizadas en tamaño y optimizadas para la extracción de características relevantes para la clasificación meteorológica.


(PODEMOS PONER ALGUNOS RECORTE COMO EJEMPLO, O LO QUE HICE DE PONER LA IMAGEN ORIGINAL Y AL LADO LAS AREAS INSPECCIONADAS Y LA SELECCIONADA)


# Preparación de Datos para Entrenamiento
 
Recordar que train y test ya estaban separados, pero (Hablar de validación)

# Entrenamiento I: Clasificación Temporal
## Clasificación Binaria: Día vs. Noche
### Análisis de Características (RGB, HSV, Desviación V)
### Selección del Mejor Modelo Binario

## Clasificación Multiclase: Añadiendo "Sunrise"
### Nuevas Características para detectar Amanecer
### Análisis de Componentes Principales (PCA)
## Modelo Final Temporal

# Entrenamiento II: Clasificación Meteorológica 
## Propuesta y Análisis de Características
## Aplicación de PCA y Selección de Modelo

# Evaluación con Conjunto de Test 
## Resultados en Clasificación Temporal
## Resultados en Clasificación Meteorológica

## Conclusiones y Líneas Futuras